Refactor test target
k8gb-io/k8gb pull request #492
Opened 2021-05-19 08:30 UTC by kuritka

`test` target runs unit tests only while `check` target runs golic + lint + test

Signed-off-by: kuritka <kuritka@gmail.com>

2021-05-19 08:35 UTC, ytsarev reviewed
In which scenarios `make check`  is going to be executed? Doesn't look obvious to me.

2021-05-19 08:51 UTC, kuritka commented
> In which scenarios `make check` is going to be executed? Doesn't look obvious to me.

It's implementation of yesterday's discussion with @somaritane, where `make test` would test doing no additional steps, while `check` is doing necessary checks. 

`make check` is an optional step but would executed before pushing to GitHub by developer. If `make check` is not executed and anything wrong, build pipeline will reveal the issue.

2021-05-19 10:15 UTC, somaritane submitted a review, later dismissed
lgtm

2021-05-19 14:24 UTC, ytsarev requested changes
Ok, then please make it visible in `make help` and probably mention it in `CONTRIBUTING.md` ?

2021-05-20 08:37 UTC, kuritka commented
> Ok, then please make it visible in `make help` and probably mention it in `CONTRIBUTING.md` ?

@ytsarev, thx amended

2021-05-20 09:01 UTC, k0da approved these changes
LGTM

2021-05-20 16:39 UTC, ytsarev approved these changes

2021-05-20 20:10 UTC, merged