terratest abstraction
k8gb-io/k8gb pull request #514
Opened 2021-06-03 10:12 UTC by kuritka

I created test absatraction for terratests. The change is backward compatible so terratests can be still written an old fashioned way.

I had to create package `terratest/utils` containing
- test abstraction
- helper functions
- TestSettings struct

Also I had to move go.mod file from terratest/test to terratest.

I removed basic failover and basic roundrobin tests and replaced by full roundrobin and full failover tests. See the table below:

|                                           | roundrobin<br>**k3d-test-gslb1 (EU)** | roundrobin<br>**k3d-test-gslb2 (US)** | failover<br>**k3d-test-gslb1 (EU)** | failover<br>**k3d-test-gslb2 (US)** |
|-------------------------------------------|:-------------------------------------:|:-------------------------------------:|:-----------------------------------:|:-----------------------------------:|
| IP of CoreDNS                             |             `10.43.18.112`            |             `10.43.56.78`             |            `10.43.18.112`           |            `10.43.56.78`            |
| Localtargets                              |            `10.43.101.181`            |            `10.43.148.142`            |           `10.43.101.181`           |           `10.43.148.142`           |
| initial state                             |   `10.43.101.181`<br>`10.43.148.142`  |   `10.43.101.181`<br>`10.43.148.142`  |           `10.43.101.181`           |           `10.43.101.181`           |
| k3d-test-gslb2, <br>`make stop-test-app`  |            `10.43.148.142`            |            `10.43.148.142`            |           `10.43.101.181`           |           `10.43.101.181`           |
| k3d-test-gslb1, <br>`make stop-test-app`  |                  `-`                  |                  `-`                  |                 `-`                 |                 `-`                 |
| k3d-test-gslb2, <br>`make start-test-app` |            `10.43.101.181`            |            `10.43.101.181`            |           `10.43.148.142`           |           `10.43.148.142`           |
| k3d-test-gslb1, <br>`make start-test-app` |   `10.43.101.181`<br>`10.43.148.142`  |   `10.43.148.142`<br>`10.43.101.181`  |           `10.43.101.181`           |           `10.43.101.181`           |

**The IP's addresses may differ*

Because the tests have more steps than before, terratest takes more time now. In the future, however, we can optimize this by running individual steps (e.g : create instance) on both clusters in parallel. This will reduce.

Signed-off-by: kuritka <kuritka@gmail.com>

2021-06-10 21:31 UTC, ytsarev commented on terratest/utils/extensions.go
> +}
@kuritka overall it looks great. Can we document the testing DLS functions in this file and/or create short documentation?

2021-06-14 10:58 UTC, ytsarev requested changes
Just quickly went through the doc but then realized that it is probably not finished. Left the comments with suggestions I spotted so far

2021-06-14 10:58 UTC, ytsarev commented on terratest/README.md
> +Terratests are another layer in k8gb testing. They test the state of k8b on tuple of clusters and examine the behavior
`s/k8b/k8gb`

2021-06-14 10:58 UTC, ytsarev commented on terratest/README.md
> +for individual usecases. They replace manual tests; install GSLB in a separate namespace and check if everything
```suggestion
for individual use cases. They replace manual tests, install GSLB in a separate namespace and check if everything 
```

2021-06-14 10:58 UTC, ytsarev commented on terratest/README.md
> +Terratest is basically a separate project inside k8gb. The tests are running as Gihub actions when interacting
```suggestion
Terratest is basically a separate project inside k8gb. The tests are running as GitHub Actions when interacting 
```

2021-06-14 10:58 UTC, ytsarev commented on terratest/README.md
> +On the other hand, the ability to quickly spin-up clusters with test applications and then easily read ip addresses
```suggestion
On the other hand, the ability to quickly spin up clusters with test applications and then easily read ip addresses 
```

2021-06-14 11:23 UTC, kuritka commented
@ytsarev, thanks for review. I amended the changes and also added test example and troubleshoot part.

2021-06-18 14:55 UTC, ytsarev approved these changes

2021-06-18 20:45 UTC, merged