Make K8gbGslbStatusPerIngressHosts metric readable
k8gb-io/k8gb pull request #587
Opened 2021-08-30 16:05 UTC by kuritka

For readibility I splited K8gbGslbStatusPerIngressHosts into three different metrics:
 - k8gb_gslb_healthy_records
 - k8gb_gslb_unhealthy_records
 - k8gb_gslb_not_found_records

The metric observes staus of GSLB serviceHealth
```json
status:
  geoTag: us
  healthyRecords:
    roundrobin.cloud.example.com:
    - 192.168.240.2
    - 192.168.240.3
  serviceHealth:
    notfound.cloud.example.com: NotFound
    roundrobin.cloud.example.com: Unhealthy
    unhealthy.cloud.example.com: Unhealthy
```

I renamed `k8gb_gslb_healthy_records` to `k8gb_endpoint_healthy_records`.
The metric observes number of endpoint targets:
```json
spec:
  endpoints:
  - dnsName: roundrobin.cloud.example.com
    labels:
      strategy: roundRobin
    recordTTL: 30
    recordType: A
    targets:
    - 192.168.240.2
    - 192.168.240.3
```

Signed-off-by: kuritka <kuritka@gmail.com>

2021-09-06 10:00 UTC, ytsarev requested changes
Some suggestions.

```
I renamed k8gb_gslb_healthy_records to k8gb_endpoint_healthy_records.

```
Also, it is not clear if above mentioned metrics should coexist and why

2021-09-07 07:51 UTC, kuritka commented
> Some suggestions.
> 
> ```
> I renamed k8gb_gslb_healthy_records to k8gb_endpoint_healthy_records.
> ```
> 
> Also, it is not clear if above mentioned metrics should coexist and why

The question is whether someone needs to monitor Service health, which doesn't say anything about guests. It only shows the number of Healthy, Unhealthy, and NotFound in time.

Similar is the DNSEndpoint tracking, do we want to monitor the number of A records ? 

@k0da , @somaritane , @jkremser, WDYT?

2021-09-10 13:45 UTC, jkremser commented
imho, the more metrics the better at the beginning. It's pretty common to deploy also k8s node exporters and a lot of info can be obtained there so probably we should not be redundant but instead report only k8gb specific metrics. Not sure if the `k8gb_gslb_healthy_records` metric can be somehow directly calculated by some smart PromQL from pods statuses, but still if I get it right it's kind of more abstract and app specific, so why not to report it.

Ideally we should come up with some list of metrics that we find useful and the others will come from people who actually use it and needs to alert on them or trying to detect some drift. I can imagine that coredns have it's own set of exported metrics as well that might be actually useful in conjunction with ours.

For my previous operators, I've been also maintaining metrics like counts of created CRs or JVM internal metrics (cos it was Java based), version of the app, gitSha, versions of tools it was compiled with, etc. The string based metrics are kind of tricky w/ Prometheus, but there is a workaround to this, using them as a label and having the value of the metrics set to something dummy like 1.

2021-09-10 14:00 UTC, somaritane commented on controllers/providers/metrics/prometheus.go
>  	m.metrics.K8gbGslbHealthyRecords = prometheus.NewGaugeVec(
I guess the metric name should be changed too in order to reflect the updated metric description ("Number of unhealthy Services observed by GSLB.")
```suggestion
	m.metrics.K8gbGslbHealthyServices = prometheus.NewGaugeVec(
```

2021-09-10 14:22 UTC, somaritane commented
> The string based metrics are kind of tricky w/ Prometheus, but there is a workaround to this, using them as a label and having the value of the metrics set to something dummy like 1.

IIRC this is exactly how the `K8gbGslbStatusPerIngressHosts` metric was organized, by using the status type ("NotFound", "Healthy", "Unhealthy") as a label, so that status count can be later found out for particular status type in a query. 
Not sure if it makes sense to split `K8gbGslbStatusPerIngressHosts` into 3 metrics.

2021-09-10 14:52 UTC, jkremser commented
> IIRC this is exactly how the K8gbGslbStatusPerIngressHosts metric was organized, by using the status type ("NotFound", "Healthy", "Unhealthy") as a label, so that status count can be later found out for particular status type in a query.

correct, but these were and still are normal gauges that stores doubles, I was more talking about string based metrics, where you would like to expose some strings, like what's the version, what's the gitSha, image tag, etc. and there is a hack for this:

you can have a metric

```
k8gb_my_fancy_runtime_info{k8gb_version="1.0.0",goLangVersion="1.17",gitSha="xyz"} 1.0
```
I.e. storing them as a key-value pairs where key is the label name and value is the label value and the real value of the metric is not important at all so it can be `1.0`, little hackish, but it's being used especially if you need this info in Grafana where you can't call `kubectl` to get the info from annotations/labels/env vars.

2021-09-10 14:57 UTC, somaritane commented
> ```
> k8gb_my_fancy_runtime_info{k8gb_version="1.0.0",goLangVersion="1.17",gitSha="xyz"} 1.0
> ```
Ah I see, looks like a good way to store project-related metadata 👍

2021-09-14 09:36 UTC, kuritka commented
@jkremser , @somaritane Thx for helpful discussion.

I think you've summed up well what is needed
 - update, metric.md
 - K8gbGslbStatusPerIngressHosts leave as it is (don't split)
 - introducing the `k8gb_runtime_info` would be sufficient
 
Basically I agree, I decided to close this PR and create a new one(s) according to the discussion.  I will probably move `k8gb_endpoint_healthy_records` to the new PR. 

@ytsarev, @k0da , @jkremser , @somaritane  shout if disagree.

2021-09-14 10:25 UTC, somaritane commented
> Basically I agree, I decided to close this PR and create a new one(s) according to the discussion. I will probably move `k8gb_endpoint_healthy_records` to the new PR.
> 
> @ytsarev, @k0da , @jkremser , @somaritane shout if disagree.

@kuritka, thanks for summing things up, the plan looks good, just one thing from my side:

> * K8gbGslbStatusPerIngressHosts leave as it is (don't split)

I think it still makes sense to improve the naming of this metric and remove the confusion about its purpose and the nature of its values.
Here's the suggestion:
`K8gbGslbStatusPerIngressHosts` -> `K8gbGslbServiceStatusCount (k8gb_gslb_service_status_count)`
What do you think?

2021-09-15 09:14 UTC, kuritka commented
Based on the discussion I have decided to close this PR and replace it with several other PRs. See log for references.

2021-09-15 09:14 UTC, closed without merging