DNS package test coverage (3/3)
k8gb-io/k8gb pull request #635
Opened 2021-09-30 15:34 UTC by kuritka

This is a follow-up PR to #630 (1/3), do not review until #630 is merged.

Thanks to the ntroducing mocks I can test what is going on inside the large functions in the DNS package.
I have written several tests that create/update the DNS record and assert values at runtime (not just asserting the error the function returns).
I managed to achieve 62% coverage. The uncovered are mostly constructor functions, single-line functions that call the assistant package directly (this is more about testing the assistant package).

Signed-off-by: kuritka <kuritka@gmail.com>

2021-10-02 19:05 UTC, k0da approved these changes

2021-10-03 09:14 UTC, ytsarev requested changes
@kuritka please rebase

2021-10-04 07:35 UTC, kuritka commented
@ytsarev, done and thx !

2021-10-04 08:21 UTC, kuritka commented on controllers/providers/dns/infoblox_test.go
> +	at "github.com/AbsaOSS/k8gb/controllers/providers/assistant"
@ytsarev , good finding. It had naming conflict before some refactorings. I corrected it. 
thx!

2021-10-04 09:49 UTC, ytsarev approved these changes

2021-10-04 09:49 UTC, merged