Push image to docker hub #651
k8gb-io/k8gb pull request #709
Opened 2021-10-30 22:15 UTC by AugustasV

Added block to upload artifact into dockerhub.
Looking for a feedback.

https://github.com/k8gb-io/k8gb/issues/651

2021-10-31 14:32 UTC, ytsarev requested changes
Thanks a lot for the contribution 👍 Curldemo is not connected to main k8gb release so it's better to create a separate flow for it. Also `env.GITHUB_JOB` will probably create unrelated tag name for the image

2021-10-31 14:34 UTC, ytsarev requested changes

2021-10-31 14:34 UTC, ytsarev commented on .github/workflows/release.yaml
> +          tags: ${{ secrets.DOCKER_USER }}/k8gb:${{ env.GITHUB_JOB }}
should be different docker repo as well.
```suggestion
          tags: ${{ secrets.DOCKER_USER }}/k8gb-demo:${{ env.GITHUB_JOB }}
```

2021-11-01 08:55 UTC, ytsarev requested changes
Please address suggested changes.

Please also use --signoff to satisfy DCO https://github.com/k8gb-io/k8gb/pull/709/checks?check_run_id=4060681862 .

We are CNCF project and it is a strong requirement.

2021-11-01 08:55 UTC, ytsarev commented on .github/workflows/curldemo.yaml
> +      - "v*"
It's not connected to main release, so it is better to execute as reaction to file patch change, see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-including-paths

2021-11-01 08:55 UTC, ytsarev commented on .github/workflows/curldemo.yaml
> +          echo "::set-output name=previous_tag::${previous_tag}"
Should not be required here as it is not connected with the release

2021-11-01 08:55 UTC, ytsarev commented on .github/workflows/curldemo.yaml
> +      - name: Run GoReleaser
no goreleaser required, we are not building any binary with curl demo

2021-11-01 08:55 UTC, ytsarev commented on .github/workflows/release.yaml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
please revert newline change

2021-11-01 09:04 UTC, jkremser requested changes

2021-11-01 22:54 UTC, AugustasV commented on .github/workflows/curldemo.yaml
> +          tags: ${{ secrets.DOCKER_USER }}/k8gb-demo:latest
Yes I know that using latest is evil, which env variable you would recommend to use? I tried right now with  GITHUB_RUN_NUMBER

2021-11-02 09:21 UTC, ytsarev commented on .github/workflows/curldemo.yaml
> +          tags: ${{ secrets.DOCKER_USER }}/k8gb-demo:latest
@jkremser `latest` is evil but imho exactly what we need for the trivial demo. Obviously open to any better suggestions but the main goal is to keep it simple.

2021-11-02 09:30 UTC, jkremser commented on .github/workflows/curldemo.yaml
> +          tags: ${{ secrets.DOCKER_USER }}/k8gb-demo:latest
make sense, kets keep it simple

2021-11-02 09:57 UTC, ytsarev requested changes

2021-11-02 09:57 UTC, ytsarev commented on .github/workflows/release.yaml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Please keep new line around

2021-11-02 09:57 UTC, ytsarev commented on .github/workflows/curldemo.yaml
> +          tags: ${{ secrets.DOCKER_USER }}/k8gb-demo-curl:$GITHUB_RUN_NUMBER
Let's stick with `latest` as we agreed in https://github.com/k8gb-io/k8gb/pull/709#discussion_r740856251

2021-11-02 12:07 UTC, jkremser requested changes

2021-11-02 12:07 UTC, jkremser commented on .github/workflows/curldemo.yaml
> +          fetch-depth: 0
```suggestion
```

nit: `fetch-depth: 0` [indicates](https://github.com/actions/checkout/blob/ec3a7ce113134d7a93b817d10a8272cb61118579/README.md?plain=1#L92) that all history, branches and tags will be fetched, but we are not doing any fancy git stuff here, so the default shallow fetch should be ok. If omitted the `1` is used

2021-11-04 08:50 UTC, jkremser approved these changes

2021-11-04 08:52 UTC, k0da approved these changes
LGTM

2021-11-04 08:53 UTC, ytsarev approved these changes
@AugustasV looks great, thanks for all the fixes :)

2021-11-05 16:32 UTC, merged