Helm values schema check
k8gb-io/k8gb pull request #950
Opened 2022-09-09 12:57 UTC by jkremser

if there is a change to `values.yaml` or `values.schema.json`, this workflow will verify that `values.yaml` file is still valid against the corresponding JSON schema.

I had to remove those `required: []` lines because the python tool was failing on them. Semantically it's the same, these lines were actually redundant.

2022-09-09 15:33 UTC, kuritka requested changes

2022-09-09 15:33 UTC, kuritka commented on .github/workflows/helm_check-values-schema.yaml
> +# thanks to https://github.com/giantswarm/devctl/blob/v5.9.0/pkg/gen/input/workflows/internal/file/check_values_schema.yaml.template for the idea
```suggestion
see: https://github.com/giantswarm/devctl/blob/v5.9.0/pkg/gen/input/workflows/internal/file/check_values_schema.yaml.template
```

2022-09-09 23:26 UTC, jkremser commented
meh, applying your suggestion broke it... the comment is missing. Will fix that on Monday + I was actually happier with the original form since it's only based on this idea, however the implementaion is totally different

2022-09-13 14:26 UTC, kuritka approved these changes
At first glance, `thanks comment` looked more like you forgot it was there. If that's what you want, it's okay.

2022-09-13 14:28 UTC, merged