Architecture diagram added
k8gb-io/k8gb pull request #960
Opened 2022-10-03 14:24 UTC by kuritka

closes #877

Signed-off-by: kuritka <kuritka@gmail.com>

2022-10-03 18:41 UTC, somaritane commented on docs/components.md
> +[![K8GB Cluster Collaboration](/docs/images/k8gb-collaboration.svg)](/docs/images/k8gb-collaboration.svg)
@kuritka not sure if "cluster collaboration" is the right term here, maybe "multi-cluster interoperability"?

2022-10-03 18:45 UTC, somaritane commented on docs/images/k8gb-collaboration.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="1813px" height="1576px" viewBox="-0.5 -0.5 1813 1576" content="&lt;mxfile host=&quot;app.diagra
The diagram description under the title still reads "Internal k8gb components and relation between them".
Should it still be the case?
![image](https://user-images.githubusercontent.com/502695/193654513-821fabfb-e889-498c-9a96-71dae2bae963.png)

2022-10-03 18:46 UTC, somaritane requested changes
@kuritka thank you for arch diagram update, looks good with a few comments from me.

2022-10-04 10:27 UTC, kuritka commented
@somaritane , @ytsarev  all required changes amended. thanks!

2022-10-04 21:48 UTC, somaritane approved these changes
@kuritka lgtm 👍

2022-10-05 10:19 UTC, merged