Use Salsa framework during release to increase the supply-chain security
k8gb-io/k8gb pull request #966
Opened 2022-10-12 14:50 UTC by jkremser

This is how it looks like on my other repo - https://github.com/jkremser/log2rbac-operator/actions/runs/3234735006#summary-8846153907

it relies on 3 new repo secrets: `COSIGN_PRIVATE_KEY`, `COSIGN_PUBLIC_KEY` and `COSIGN_PASSWORD`
`COSIGN_PASSWORD` is a passphrase for the private key. The private key is used for signing the artifacts (container images, provenance files, sboms, checksums). The public key is also part of the repo and is used for verifying the signatures.

During the release we push the signatures of container images into container registries so that one can verify the validity of the image. Also some artifacts are published together with the release, check the Assets section on [log2rbac release](https://github.com/jkremser/log2rbac-operator/releases/tag/v0.0.5) page.

inspired / kudos to https://github.com/philips-labs/slsa-provenance-action/blob/main/.github/workflows/ci.yaml

Signed-off-by: Jirka Kremser <jiri.kremser@gmail.com>

2022-10-15 05:44 UTC, kuritka approved these changes
Lgtm

2022-10-15 12:22 UTC, somaritane requested changes
@jkremser looks awesome! 
I suggest reflecting these changes in the dev documentation, also wrt the case when cosign key pair should be regenerated.

2022-10-15 12:22 UTC, somaritane commented on cosign.pub
> +-----BEGIN PUBLIC KEY-----
just  thinking, what should be the procedure for cosign key pair regeneration

2022-10-17 13:54 UTC, ytsarev approved these changes
@jkremser it looks really really good. Is it possible to have brief contextual documentation for the implementation? Fine to have it as a separate PR.

2022-10-17 16:13 UTC, ytsarev approved these changes

2022-10-17 16:32 UTC, kuritka approved these changes

2022-10-17 17:24 UTC, jkremser commented
@somaritane I've added the docs, can you "ptal" again?

2022-10-17 18:30 UTC, somaritane approved these changes
@jkremser lgtm now, thank you!

2022-10-17 18:43 UTC, merged